# Generated by Django 6.0.5 on 2026-05-19 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccidentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("day_of_week", models.CharField(max_length=20)),
                ("weather_condition", models.CharField(max_length=50)),
                ("road_type", models.CharField(max_length=50)),
                ("light_condition", models.CharField(max_length=50)),
                ("speed_limit", models.IntegerField(blank=True, null=True)),
                (
                    "junction_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("severity", models.CharField(max_length=20)),
                ("number_of_vehicles", models.IntegerField(default=1)),
                ("number_of_casualties", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UK_STATS19", "UK STATS19"),
                            ("KTM_SYNTHETIC", "Kathmandu Synthetic"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HotspotCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centroid_latitude", models.FloatField()),
                ("centroid_longitude", models.FloatField()),
                ("centroid_location", models.TextField(blank=True, null=True)),
                ("accident_count", models.IntegerField()),
                ("radius", models.FloatField()),
                ("average_severity", models.FloatField()),
                ("peak_time", models.CharField(blank=True, max_length=20, null=True)),
                ("peak_day", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "dominant_weather",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("record_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
