# Generated by Django 6.0.5 on 2026-05-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentrecord",
            name="source",
            field=models.CharField(
                choices=[
                    ("UK_STATS19", "UK STATS19"),
                    ("KTM_SYNTHETIC", "Kathmandu Synthetic"),
                    ("KTM_SCRAPED", "Kathmandu Scraped"),
                ],
                max_length=20,
            ),
        ),
    ]
