# Generated by Django 6.0.5 on 2026-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0002_alter_accidentrecord_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentrecord",
            name="accident_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="accidentrecord",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accidentrecord",
            name="location_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="accidentrecord",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accidentrecord",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
