# Generated by Django 6.0.5 on 2026-05-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0003_accidentrecord_accident_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentrecord",
            name="number_of_deaths",
            field=models.IntegerField(default=0),
        ),
    ]
