# Generated by Django 6.0.5 on 2026-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0005_remove_pointfields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentrecord",
            name="road_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
