# Generated by Django 6.0.5 on 2026-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidents", "0006_alter_accidentrecord_road_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accidentrecord",
            name="light_condition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
