# Generated by Django 6.0.5 on 2026-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0007_alter_accidentrecord_light_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('f1_macro', models.FloatField()),
                ('confusion_matrix_json', models.TextField()),
                ('per_class_metrics_json', models.TextField()),
                ('train_size', models.IntegerField()),
                ('test_size', models.IntegerField()),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
